image: trion/ng-cli-e2e:8.1.2

# Defining some variables rather than repeating them everywhere.
variables:
  IMAGE_NAME: us.gcr.io/elypia/elypia-website
  SERIALIZED_IMAGE: elypia-website-image.tar

stages:
  - test
  - build-website
  - build-docker
  - deploy

# Run all tests and make sure we're happy with the commit.
test:
  stage: test
  script:
    - npm install
    - npm rebuild node-sass
    - npm run-script check
  cache:
    paths:
      - node_modules/

# Compile the website into static assets.
build-website:
  stage: build-website
  script:
    - npm run-script build --prod
  cache:
    paths:
      - dist/
      - node_modules/

# Build the Dockerfile, this isn't used anywhere, we just want to make sure it still builds.
build-docker:
  stage: build-docker
  image: docker
  services:
    - docker:dind
  script:
    - docker build -t ${IMAGE_NAME}:latest .
    - mkdir images
    - docker save ${IMAGE_NAME} > images/${SERIALIZED_IMAGE}
  cache:
    policy: pull-push
    paths:
      - dist/
      - images/

# Deploy our new Docker Image and Kubernetes cluster configuration.
deploy:
  only:
    - tags
  stage: deploy
  image: google/cloud-sdk
  script:
    - docker load -i images/${SERIALIZED_IMAGE}
    - docker tag ${IMAGE_NAME}:latest ${IMAGE_NAME}:${CI_COMMIT_TAG}
    - echo $GCP_SA_KEY > /tmp/${CI_PIPELINE_ID}.json
    - gcloud auth configure-docker --quiet
    - gcloud auth activate-service-account --key-file /tmp/${CI_PIPELINE_ID}.json
    - docker push ${IMAGE_NAME}:${CI_COMMIT_TAG}
    - rm /tmp/${CI_PIPELINE_ID}.json
  cache:
    policy: pull
    paths:
      - images/
