image: trion/ng-cli-e2e:8.2.1

# Defining some variables rather than repeating them everywhere.
variables:
  IMAGE_NAME: us.gcr.io/elypia/elypia-website
  SERIALIZED_IMAGE: elypia-website.tar

stages:
  - init
  - test
  - build
  - deploy

# All cache are uploaded and downloaded everywhere to avoids
# tasks or other builds from removing eachothers files.
cache:
  policy: pull-push
  paths:
    - dist/
    - images/
    - node_modules/

init:
  stage: init
  script:
    - npm install
    - npm rebuild node-sass

lint:
  stage: test
  script:
    - npm run-script lint
  cache:
    policy: pull
    paths:
      - node_modules/

test:
  stage: test
  script:
    - npm run-script test
  cache:
    policy: pull
    paths:
      - node_modules/

e2e:
  stage: test
  script:
    - npm run-script e2e
  cache:
    policy: pull
    paths:
      - node_modules/

# Compile the website into static assets.
build:
  stage: build
  services:
    - docker:19.03.1-dind
  script:
    - npm run-script build --prod
    - docker build -t ${IMAGE_NAME}:latest .
    - mkdir -p images
    - docker save ${IMAGE_NAME} > images/${SERIALIZED_IMAGE}

# Deploy our new Docker Image and Kubernetes cluster configuration.
deploy:
  only:
    - tags
  stage: deploy
  image: docker:19.03.1
  services:
    - docker:19.03.1-dind
  script:
    - docker load -i images/${SERIALIZED_IMAGE}
    - docker tag ${IMAGE_NAME}:latest ${IMAGE_NAME}:${CI_COMMIT_TAG}
    - cat ${GCP_SA_KEY} | docker login -u _json_key --password-stdin https://us.gcr.io
    - docker push ${IMAGE_NAME}:${CI_COMMIT_TAG}
  cache:
    policy: pull
    paths:
      - images/
