# The configuration assumes a the Kubernetes cluster has Helm installed
# with the following charts (packages):
# * nginx-ingress - Load balancer to internal web applciation instances.
# * cert-manager - Automatically provisions Let's Encrypt SSL certificates.

---
# Deploy the Elypia Website
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elypia-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elypia-website
  template:
    metadata:
      labels:
        app: elypia-website
    spec:
      volumes:
        - name: client-certificate
          secret:
            secretName: client-certificate
      containers:
        - name: elypia-website
          image: us.gcr.io/elypia/elypia-website:{{CI_COMMIT_TAG}}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
          volumeMounts:
            - name: client-certificate
              mountPath: /etc/nginx/client-certificate.pem
          readinessProbe:
            httpGet:
              path: /index.html
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 5
            periodSeconds: 15
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /index.html
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 5
            periodSeconds: 15
            failureThreshold: 3
---
